export default {
  container: {
    maxWidth: '1200px',
  },
  height:{
    default: '100vh',
    max: '736px',
  },
  width:{
    max: '375px',
  },
  grid: {
    container: '130rem',
    gutter: '3.2rem',
  },
  layers: {
    before: -10,
    background: 0,
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
  font: {
    family:
      'NibPro, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif',
    primary: 'sans-serif',
    secondary: 'NibPro',
    sizes: {
      xxxsmall: '9px',
      xxsmall: '12px',
      xsmall: '14px',
      small: '16px',
      medium: '18px',
      large: '20px',
      xlarge: '22px',
      xxlarge: '25px',
      xxxlarge: '30px',
      larger: '33px',
      xxlarger: '35px',
      xxxlarger: '40px',
      huge: '60px',
      xhuge: '65px',
      xxhuge: '70px',
      xxxhuge: '80px',
    },
    colors: {
      primary: '#4D4D4D',
      secondary: '#7FA2CB',
      button: '#E6E6E6',
      white: '#fdfdfd',
    },
  },
  colors: {
    primary: '#67635C',
    primaryHover: '#7FA2CB',
    secondary: '#ffff',
    mainBg: '#ffff',
    darkBrownBg: '#67635C',
    lightBrownBg: '#75726C',
    boxBg: '#FAFAFA',
    softWhite: '#F4F4F4',
    texts: '#030517',
    white: '#FFFFFF',
    black: '#121212',
    green: '#C2E763',
    greenOpacity: '#C2E763AC',
    gray: '#cfcfcf',
    darkGray: '#707070A6',
    footer: '#4D4D4D'
  },
  spacings: {
    xxsmall: '5px',
    xsmall: '10px',
    small: '15px',
    medium: '20px',
    large: '40px',
    xlarge: '60px',
    xxlarge: '70px',
  },
};
